<?php

return [
    [
        'item_name' => 'Laptop Computer',
        'description' => '15.6-inch laptop, Intel Core i5, 16GB RAM, 512GB SSD',
        'unit' => 'unit',
        'unit_cost' => 45000,
    ],
    [
        'item_name' => 'Desktop Computer',
        'description' => 'Intel Core i7 desktop computer with 16GB RAM and 1TB SSD',
        'unit' => 'unit',
        'unit_cost' => 55000,
    ],
    [
        'item_name' => 'Computer Set',
        'description' => 'Desktop computer package including monitor, keyboard, and mouse',
        'unit' => 'set',
        'unit_cost' => 65000,
    ],
    [
        'item_name' => 'LED Monitor',
        'description' => '24-inch Full HD LED monitor',
        'unit' => 'pcs',
        'unit_cost' => 8500,
    ],
    [
        'item_name' => 'Keyboard',
        'description' => 'USB wired keyboard',
        'unit' => 'pcs',
        'unit_cost' => 850,
    ],
    [
        'item_name' => 'Optical Mouse',
        'description' => 'USB optical mouse',
        'unit' => 'pcs',
        'unit_cost' => 450,
    ],
    [
        'item_name' => 'Laser Printer',
        'description' => 'Monochrome network laser printer',
        'unit' => 'unit',
        'unit_cost' => 12000,
    ],
    [
        'item_name' => 'Document Scanner',
        'description' => 'High-speed document scanner',
        'unit' => 'unit',
        'unit_cost' => 18000,
    ],
    [
        'item_name' => 'Photocopier Machine',
        'description' => 'Heavy-duty multifunction photocopier',
        'unit' => 'unit',
        'unit_cost' => 95000,
    ],
    [
        'item_name' => 'LCD Projector',
        'description' => 'Full HD multimedia projector',
        'unit' => 'unit',
        'unit_cost' => 28000,
    ],
    [
        'item_name' => 'Projector Screen',
        'description' => 'Pull-down projection screen',
        'unit' => 'pcs',
        'unit_cost' => 6500,
    ],
    [
        'item_name' => 'Smart Television',
        'description' => '55-inch UHD Smart TV',
        'unit' => 'unit',
        'unit_cost' => 32000,
    ],
    [
        'item_name' => 'WiFi Router',
        'description' => 'Dual-band wireless router',
        'unit' => 'unit',
        'unit_cost' => 4500,
    ],
    [
        'item_name' => 'Network Switch',
        'description' => '24-port Gigabit managed switch',
        'unit' => 'unit',
        'unit_cost' => 9500,
    ],
    [
        'item_name' => 'UPS',
        'description' => '1500VA uninterrupted power supply',
        'unit' => 'unit',
        'unit_cost' => 6500,
    ],
    [
        'item_name' => 'Office Desk',
        'description' => 'Wooden office desk with drawers',
        'unit' => 'pcs',
        'unit_cost' => 9000,
    ],
    [
        'item_name' => 'Office Chair',
        'description' => 'Ergonomic office chair',
        'unit' => 'pcs',
        'unit_cost' => 4500,
    ],
    [
        'item_name' => 'Conference Table',
        'description' => 'Large conference table for meetings',
        'unit' => 'pcs',
        'unit_cost' => 18000,
    ],
    [
        'item_name' => 'Filing Cabinet',
        'description' => 'Four-drawer steel filing cabinet',
        'unit' => 'pcs',
        'unit_cost' => 8500,
    ],
    [
        'item_name' => 'Bookshelf',
        'description' => 'Steel bookshelf with multiple compartments',
        'unit' => 'pcs',
        'unit_cost' => 6000,
    ],
    [
        'item_name' => 'Air Conditioning Unit',
        'description' => '2.0 HP inverter air conditioning system',
        'unit' => 'unit',
        'unit_cost' => 42000,
    ],
    [
        'item_name' => 'Electric Fan',
        'description' => 'Industrial stand fan',
        'unit' => 'pcs',
        'unit_cost' => 2500,
    ],
    [
        'item_name' => 'Water Dispenser',
        'description' => 'Hot and cold water dispenser',
        'unit' => 'unit',
        'unit_cost' => 5500,
    ],
    [
        'item_name' => 'Biometric Attendance Machine',
        'description' => 'Fingerprint attendance recording device',
        'unit' => 'unit',
        'unit_cost' => 15000,
    ],
    [
        'item_name' => 'CCTV Camera',
        'description' => '1080p security camera with night vision',
        'unit' => 'pcs',
        'unit_cost' => 4500,
    ],
    [
        'item_name' => 'Public Address System',
        'description' => 'Audio system with amplifier and speakers',
        'unit' => 'set',
        'unit_cost' => 35000,
    ],
    [
        'item_name' => 'Wireless Microphone',
        'description' => 'Dual-channel wireless microphone system',
        'unit' => 'set',
        'unit_cost' => 6500,
    ],
    [
        'item_name' => 'Web Camera',
        'description' => '1080p USB webcam for meetings and classes',
        'unit' => 'pcs',
        'unit_cost' => 3200,
    ],
    [
        'item_name' => 'Generator Set',
        'description' => 'Portable diesel-powered generator',
        'unit' => 'unit',
        'unit_cost' => 85000,
    ],
    [
        'item_name' => 'Operations Manual',
        'description' => 'Printed operations and maintenance manual',
        'unit' => 'copy',
        'unit_cost' => 500,
    ],
];