<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('saml_configurations', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('entity_id')->unique();
            $table->string('sso_url');
            $table->string('slo_url')->nullable();
            $table->longText('x509_cert');
            $table->longText('metadata_xml')->nullable();
            $table->string('default_relay_state')->nullable();
            $table->string('status')->default('active')->index();
            $table->boolean('is_active')->default(false)->index();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamps();
        });

        Schema::create('saml_replay_records', function (Blueprint $table) {
            $table->id();
            $table->string('assertion_id')->nullable()->unique();
            $table->string('response_id')->nullable()->unique();
            $table->string('request_id')->nullable()->unique();
            $table->string('issuer')->nullable();
            $table->timestamp('expires_at')->index();
            $table->timestamps();
        });

        Schema::create('saml_audit_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('saml_configuration_id')->nullable()->constrained()->nullOnDelete();
            $table->string('event_name');
            $table->string('entity_id')->nullable();
            // users.id was created with increments(), which is UNSIGNED INT
            // rather than the UNSIGNED BIGINT generated by foreignId().
            $table->unsignedInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->nullOnDelete();
            $table->string('request_id')->nullable();
            $table->string('response_id')->nullable();
            $table->string('ip_address')->nullable();
            $table->string('outcome')->default('success');
            $table->json('metadata')->nullable();
            $table->timestamps();
            $table->index(['event_name', 'outcome']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('saml_audit_events');
        Schema::dropIfExists('saml_replay_records');
        Schema::dropIfExists('saml_configurations');
    }
};
